import Head from 'next/head'
import { Layout } from 'components/Layout'
import { NavBar } from 'components/NavBar'
import PokeCardSmall from 'components/PokeCardSmall'
import { useState, useEffect } from 'react'

export default function Home() {
  //TODO: Meter todo en un context y hacer paginacion mas sencilla
  const [pokemonsUrls, setPokemonUrls] = useState(null)
  const [fetchURL, setFetchURL] = useState(
    'https://pokeapi.co/api/v2/pokemon?limit=151&offset=151'
  )
  const [next, setNext] = useState('')
  const [prev, setPrev] = useState('')

  useEffect(() => {
    fetch(fetchURL)
      .then((res) => res.json())
      .then((response) => {
        const { previous, next, results } = response
        const pokemonsArr = results.map((pokemon) => pokemon.url)
        setPokemonUrls(pokemonsArr)
        console.log('prev', prev)
        console.log('next', next)
        setPrev(previous)
        setNext(next)
      })
  }, [fetchURL])

  const pokemonsCards = pokemonsUrls?.map((pokemonUrl) => (
    <PokeCardSmall
      key={pokemonUrl}
      pokemonUrl={pokemonUrl}
    />
  ))

  return (
    <Layout>
      <Head>
        <title>Pokedex App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
      </Head>
      <NavBar
        next={next}
        prev={prev}
      />
      <h1 className='text-white text-center text-xl md:text-2xl lg:text-5xl'>
        Generation I
      </h1>
      <div className='my-6 mx-auto container grid gap-3 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 place-content-center'>
        {pokemonsCards}
      </div>
    </Layout>
  )
}
